services:
  localstack:
    container_name: localstack_dev
    image: localstack/localstack:latest
    ports: 
      - '4566:4566'
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './localstack:/localstack'