services:
  localstack:
    container_name: localstack_dev
    image: localstack/localstack:latest
    ports: 
      - '127.0.0.1:4566:4566'
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1